export const DATA_FETCH_START = 'DATA_FETCH_START';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_FETCH_FAILED = 'DATA_FETCH_FAILED';

export const ADD_NEW_LIST = 'ADD_NEW_LIST';
export const REMOVE_LIST = 'REMOVE_LIST';
export const MARK_LIST_EDITABLE = 'MARK_LIST_EDITABLE';
export const MARK_LIST_NOT_EDITABLE = 'MARK_LIST_NOT_EDITABLE';
export const ADD_NEW_LIST_POPUP_SHOW = 'ADD_NEW_LIST_POPUP_SHOW';
export const ADD_NEW_LIST_POPUP_HIDE = 'ADD_NEW_LIST_POPUP_HIDE';

export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const TASK_EDIT_START = 'TASK_EDIT_START';
export const TASK_EDIT_SUCCESS = 'TASK_EDIT_SUCCESS';
export const TASK_EDIT_FAILED = 'TASK_EDIT_FAILED';
export const MARK_TASK_EDITABLE = 'MARK_TASK_EDITABLE';
export const MARK_TASK_NOT_EDITABLE = 'MARK_TASK_NOT_EDITABLE';
export const REMOVE_TASK = 'REMOVE_TASK';
export const TASK_ADD_POPUP_SHOW = 'TASK_ADD_POPUP_SHOW';
export const TASK_ADD_POPUP_HIDE = 'TASK_ADD_POPUP_HIDE';
export const TASK_EDIT_POPUP_SHOW = 'TASK_EDIT_POPUP_SHOW';
export const TASK_EDIT_POPUP_HIDE = 'TASK_EDIT_POPUP_HIDE';
