export const DATA_FETCH_START = 'DATA_FETCH_START';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_FETCH_FAILED = 'DATA_FETCH_FAILED';

export const LIST_ADD_START = 'LIST_ADD_START';
export const LIST_ADD_SUCCESS = 'LIST_ADD_SUCCESS';
export const LIST_ADD_FAILED = 'LIST_ADD_FAILED';
export const LIST_REMOVE_START = 'LIST_REMOVE_START';
export const LIST_REMOVE_SUCCESS = 'LIST_REMOVE_SUCCESS';
export const LIST_REMOVE_FAILED = 'LIST_REMOVE_FAILED';
export const MARK_LIST_ACTIVE = 'MARK_LIST_ACTIVE';
export const MARK_LIST_NOT_ACTIVE = 'MARK_LIST_NOT_ACTIVE';

export const TASK_ADD_START = 'TASK_ADD_START';
export const TASK_ADD_SUCCESS = 'TASK_ADD_SUCCESS';
export const TASK_ADD_FAILED = 'TASK_ADD_FAILED';
export const TASK_EDIT_START = 'TASK_EDIT_START';
export const TASK_EDIT_SUCCESS = 'TASK_EDIT_SUCCESS';
export const TASK_EDIT_FAILED = 'TASK_EDIT_FAILED';
export const MARK_TASK_ACTIVE = 'MARK_TASK_ACTIVE';
export const MARK_TASK_NOT_ACTIVE = 'MARK_TASK_NOT_ACTIVE';
export const TASK_REMOVE_START = 'TASK_REMOVE_START';
export const TASK_REMOVE_SUCCESS = 'TASK_REMOVE_SUCCESS';
export const TASK_REMOVE_FAILED = 'TASK_REMOVE_FAILED';

export const USERS_WERE_UPDATED = 'USERS_WERE_UPDATED';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
